//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INF272AdminSubsystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExpertModule
    {
        public int Expert_Module_ID { get; set; }
        public Nullable<int> Expert_ID { get; set; }
        public Nullable<int> Module_ID { get; set; }
    
        public virtual Expert Expert { get; set; }
        public virtual Module Module { get; set; }
    }
}
