//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INF272AdminSubsystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LearningMaterial
    {
        public int Learning_Material_ID { get; set; }
        public string Learning_Material_Description { get; set; }
        public Nullable<int> Learning_Matterial_Type_ID { get; set; }
        public Nullable<int> Module_ID { get; set; }
    
        public virtual LearningMaterialType LearningMaterialType { get; set; }
        public virtual Module Module { get; set; }
    }
}
