//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INF272AdminSubsystem.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProjectEntities : DbContext
    {
        public ProjectEntities()
            : base("name=ProjectEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Expert> Experts { get; set; }
        public virtual DbSet<ExpertModule> ExpertModules { get; set; }
        public virtual DbSet<LearningMaterial> LearningMaterials { get; set; }
        public virtual DbSet<LearningMaterialType> LearningMaterialTypes { get; set; }
        public virtual DbSet<Mark> Marks { get; set; }
        public virtual DbSet<Memo> Memos { get; set; }
        public virtual DbSet<Module> Modules { get; set; }
        public virtual DbSet<ModuleStudent> ModuleStudents { get; set; }
        public virtual DbSet<PasswordHistory> PasswordHistories { get; set; }
        public virtual DbSet<School> Schools { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<SystemAdmin> SystemAdmins { get; set; }
        public virtual DbSet<SystemUser> SystemUsers { get; set; }
        public virtual DbSet<Teacher> Teachers { get; set; }
        public virtual DbSet<Test> Tests { get; set; }
        public virtual DbSet<TestType> TestTypes { get; set; }
    }
}
