//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INF272AdminSubsystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Test
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Test()
        {
            this.Marks = new HashSet<Mark>();
            this.Memos = new HashSet<Memo>();
        }
    
        public int Test_ID { get; set; }
        public string Test_Desccription { get; set; }
        public System.DateTime Test_Date { get; set; }
        public int Test_Total { get; set; }
        public Nullable<int> Test_Type_ID { get; set; }
        public Nullable<int> Module_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mark> Marks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Memo> Memos { get; set; }
        public virtual Module Module { get; set; }
        public virtual TestType TestType { get; set; }
    }
}
